/**
 * Rolling memory for one pill. We keep a short list of recent events
 * (verbalised in second person) and periodically summarise older ones
 * into a long-term blob. The summary itself can be regenerated by an LLM
 * later; for now it's a deterministic concatenation, but the interface
 * is set up so we can swap that in trivially.
 */

export interface Memory {
  /** Most recent first, capped. Strings like "tick 42: You picked up bread." */
  short: { tick: number; text: string }[];
  /** Compressed older history. */
  long: string;
}

const SHORT_CAP = 30;
/** Hard cap on the long-term blob, in characters. Anything older drops. */
const LONG_CAP = 6000;

export function makeMemory(): Memory {
  return { short: [], long: "" };
}

export function rememberShort(mem: Memory, tick: number, text: string): void {
  mem.short.unshift({ tick, text });
  if (mem.short.length > SHORT_CAP) {
    // Move overflow into long-term, with a one-line summary per chunk.
    const overflow = mem.short.splice(SHORT_CAP);
    const compact = overflow.map(e => `t${e.tick}: ${e.text}`).join(" | ");
    mem.long = mem.long ? `${mem.long}\n${compact}` : compact;
    if (mem.long.length > LONG_CAP) {
      // Drop oldest content; keep a "[memory truncated]" marker so the agent
      // sees that history exists but isn't fully recalled.
      mem.long = `[memory truncated]\n${mem.long.slice(-LONG_CAP)}`;
    }
  }
}

export function renderMemory(mem: Memory, maxChars = 1200): string {
  const recent = mem.short.map(e => `tick ${e.tick}: ${e.text}`).join("\n");
  const head = mem.long ? `[earlier]\n${mem.long.slice(-600)}\n\n[recent]\n` : "[recent]\n";
  const out = head + recent;
  return out.length > maxChars ? out.slice(-maxChars) : out;
}
